### ISSUE TITLE
Consider adding a couple of additional HTTP status codes

### ISSUE THREAD

**Issue by twwilliams** [j9t/web-development-glossary-forum#10]
418 "I'm a teapot" HTTP status code

503 "Service Unavailable" HTTP status code

**Comment by j9t** [comment]
Yes—I suppose the glossary could handle all of them. Thanks for raising this (and nice one with 418, that should absolutely be in the book)!

**Comment by j9t** [comment]
I hope to look at this shortly.

* Mandatory: Include codes in https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
* Optional: Augment list by special codes from https://en.wikipedia.org/wiki/List_of_HTTP_status_codes and https://httpstatuses.com/

**Comment by j9t** [comment]
Synced the glossary with RFC 2616 codes. Will review other codes to see which ones also to include.

@twwilliams, I hope you’re okay if I thank you in the acknowledgements, with a link to your website?

**Comment by j9t** [comment]
Went through other (non-experimental) HTTP status codes. All covered in version 1.3.22 of the glossary, to be published within the next few days (first on Leanpub).

Thank you for bringing this up, @twwilliams!

**Comment by twwilliams** [comment]
I'm happy with the acknowledgment. Thank you for that and for this change to the glossary.

**Comment by j9t** [comment]
Absolutely. Thank you!
