### ISSUE TITLE
missing closing </p> tag

### ISSUE THREAD

**Issue by mprizzuto** [j9t/web-development-glossary-forum#13]
On page 14 (in the.pdf version) for the definition of _Anonymous block box_  there is a missing closing `</p>` tag. I included the code snippet below
`<div>Some text<p>More text</div>`

**Comment by j9t** [comment]
Thanks @mprizzuto! This is actually correct—i.e., valid (the [`</p>` end tag is optional](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element))—and intended ([as an HTML writing style](https://meiert.com/en/blog/write-html/)).
