### ISSUE TITLE
Update "Mozilla Developer Network (MDN)" to correct name

### ISSUE THREAD

**Issue by chrisdavidmills** [j9t/web-development-glossary-forum#3]
We changed names a while ago "Mozilla Developer Network (MDN)" should be changed to "MDN Web Docs".

**Comment by j9t** [comment]
Oh I wondered about that—I found it useful to explain and expand “MDN”, and “Mozilla Developer Network (MDN) Web Docs” then turned a little unwieldy, and so “MDN” prevailed.

Have you moved away entirely from just “MDN” and the expanded form?

**Comment by chrisdavidmills** [comment]
We've moved away from the expanded form entirely, but we do still call it MDN informally.

**Comment by j9t** [comment]
I just went through (I believe) all places to switch to “MDN Web Docs.” Thanks for the extra context and filing this!
